version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: nginx
    container_name: nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html
    depends_on:
      - wordpress
    networks:
      - my_network

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    image: wordress
    container_name: wordpress
    volumes:
      - wordpress_data:/var/www/html
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=wp_user
      - WORDPRESS_DB_PASSWORD=wp_pass
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - mariadb
    networks:
      - my_network

  mariadb:
    build:
      context: .
      dockerfile: Dockerfile.mariadb
    image: mariadb
    container_name: mariadb
    environment:
      - MYSQL_ROOT_PASSWORD=root_pass
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wp_user
      - MYSQL_PASSWORD=wp_pass
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - my_network

networks:
  my_network:
    name: my_network
    driver: bridge

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/test2.bk/wordpress
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /root/test2.bk/mariadb
